### ISSUE TITLE
Include firefox with container

### ISSUE THREAD

**Issue by kpostekk** [pjatk21/sigma-api#43]
In case of container crash, firefox would exit. This would reduce number of errors related to the "reusing" session for geckodriver.

**Comment by rafalopilowski1** [comment]
Alright, as Docker image can have only one `ENTRYPOINT`, I would launch `geckodriver` and `firefox` via `std::process`, which will allow to close container (+ all dependent processes) at once.

**Comment by rafalopilowski1** [comment]
Not relevant, as we're switching to HTTP-based scrapping. Closing
